### ISSUE TITLE
Users can download selected works from their profiles

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/aggie-experts#122]
Currently our users can download their entire list of publications as a RIS file. The next steps to improve this functionality would be to allow them to select which publications to export and extend these functionalities to grants.

1. Users who have logged in navigate to their profiles. In the publication section they can either select all publications or individual publications and then export those as a RIS file. 
 * Users should be able to use the "show more" button without losing the selected publications. 
 * Currently Conference Papers are exported without dates. Recent changed in metadata formatting should resolve that. QA testing needs to include review specifically of conference paper export.
 * We have not tested book/ chapter work type import into MIV. We'll need to cross-walk Book Authored, Book Chapter, Book Edited (maybe Book reviewed) to the roles associated with a Book/ Chapter work type. Requires contacting the MIV team, and additional testing.
2. Similarly, users should be able to export their list of grants. However, the exported file format should be a CSV.
 * Users should be able to click on an "export all" option or on individual grants. 
 * Users should be able to use the "show more" button without losing the selected grants.
 * The export is a CSV file. It should contain all fields available about the grant: Title, A column for the user's name and role in the grant. A column for the remaining known contributors names and column for the remaining known contributors' roles (discuss the impact on data). If no others are known, add NA in those columns. Start date. End date. Grant Agency (awarded by). {What do we want to do about pass-through grants?}. Grant number if available or NA. Is there a way to find out if the grant has been renewed over the years? Grant Admin or NA--discuss. We need to include a readme for a number of fields here--in particular Grant Admin, the reason why there may be another university listed as the Grant Agency, that the list of contributors may be incomplete, and that the records compacts together any renewals with the original grant.

The work here includes UI design, metadata cross-walk, user-facing documentation and front-end development.

**Comment by wrenaria** [comment]
On profile: Profile owners will be able to download works individually or in bulk. "Download" icon button on main profile will download entire set of works. On the management view, "select all" will select all items showing on that page. Users may then navigate to page two and select all works to add more works to selection, retaining the page one selection. In this way, a user may select any number of pages of works before pressing the download button to obtain the set.

On search: "Select all" selects that page's set of results. Users may change display to show 25, 50, or 100 results. (Altered from 20 to 25 for clean escalation in choices -- Please make base number for any page 25 for consistency across application). 

Figma Designs are updated to reflect this on [Search](https://www.figma.com/file/VFlaWRDVaiF1lOeQu9NEW4/Aggie-Experts?type=design&node-id=104-7678&mode=design) and [MVP](https://www.figma.com/file/VFlaWRDVaiF1lOeQu9NEW4/Aggie-Experts?type=design&node-id=1639-23073&mode=design).

**Comment by Vensberg** [comment]
Definition of Done for publications:

- [ ] Users can export all publications in RIS format; Download link works
- [ ] RIS file can be imported into MIV (test article, conference paper, book / book chapter)
- [ ] Users should be able to go to the next page without losing the selected publications
- [ ] Link for Roles goes to ODR
- [ ] Link for websites goes to Elements
- [ ] Edit works link goes to a work page
- [ ] See all works link works
- [ ] Citations on landing page are APA 
- [ ] UI conforms to mockups

**Comment by Vensberg** [comment]
@UcDust , when I navigate to the edit page of works, select a work on page one, then go to page 2, the work in that position on page two is already checked selected. The download works correctly, downloading only the truly selected work.

**Comment by Vensberg** [comment]
@UcDust the download file from sandbox is not RIS File (.ris). The one that gets downloaded from rc works fine.

**Comment by qjhart** [comment]
@UcDust , let;'s name that file, `works.ris` not `data.txt`, @Vensberg did you try renaming the file, and continuing your testing?

**Comment by Vensberg** [comment]
I tried changing the name to .ris, but the properties still identified the file as text. The one downloaded from rc is identified as RIS (.ris).

**Comment by qjhart** [comment]
@Vensberg not sure what that means. This imported nicely into Zotero.  Are you saying the MIV import specifically isn't working?

**Comment by Vensberg** [comment]
Yes, MIV is the issue.

**Comment by UcDust** [comment]
@Vensberg 
This last merge should include

1. Exported file on person page for works should be renamed from `data.txt` to `works.ris`
2. `(n.d.).` is removed from citation APA
3. Exported works should have `DA` dates.

The issue you mentioned previously about checkboxes in the works list not working as expected when navigating between pagination pages should be addressed already. That was an issue with the build bundling. If you check boxes on page 1 and go to page 2 and check others, the checked works should persist, and also be what's in the download file.
