### ISSUE TITLE
Grants Management via Elements

### ISSUE THREAD

**Issue by qjhart** [ucd-library/aggie-experts#133]
This overall story is to investigate how we can incorporate the CDL Elements grants management software as the source for 
UCD grants information. There are three main components to that; 1) API access to the grants information 2) User control over grants visibility in the Elements software, and 3) management of the feeds to Elements.

## API Access

- [x] #136

- Verify that the visiibility flag is included in this.
- Christine Davis grants

- Verify visibility for jrmerz

- include a plan to incorporate QA data into our production feed

- [x] Update experts-cdl with a splay for grants [qh]

-[ ] #222

## Visibility 

- [x] Grant feed visibility (RPGO Grants and Christin(a?) Davis).  Verify that the user can affect a grants vi
- [x] Grant visibility for Manually created grant, where Justin Is co-PI of a grant

## Feed Information 

- [x] #144
Include both the scripting, (VIVO select queries) and a pointer to a google sheet holding the data

- [x] #143
- [x] #245
