### ISSUE TITLE
Aggie Expert V2 imports user profiles from UCD IAM

### ISSUE THREAD

**Issue by rakunkel-ucd** [ucd-library/aggie-experts#18]
### Discussed in https://github.com/ucd-library/aggie-experts/discussions/17

<div type='discussions-op-text'>

<sup>Originally posted by **rakunkel-ucd** February 17, 2023</sup>
AE user profiles are imported from UCD IAM identity management system via the IAM API(s).

The goal of this story is to demonstrate that we are using the FIN, fcrepo repository as the canonical data for AE.  This is the initial demonstration of that functionality.  User profile information will be imported from IAM, formatted to a filesystem, and then we will use the fin-cli to import that to the Aggie Expert backend.

Previously, IAM information was stored into a local Fuseki database, and then a construction was added to the centralized database. In the new method, (for now) we can save the IAM data as a jsonld file, and then run an arq command to convert that again, to the format that we want to import into AE. So  for the import script, the task will be: 

 - Download IAM subset using the profiles API
 - use the jena arq command to convert the data into VIVO format 
 - save this data into an AE server via the LDP protocol.
 - - potentially via the fini-cli import utility.

## Tasks

One ancillary issue about this is getting our profile access figured out.
- [x] https://github.com/qjhart/ucdi/issues/8
- [x] Construct jsonld profile file for FIN CLI ingest
- [ ] Investigate NodeJS version of jsonld file construction
- [x] Get an initial docker-compose file developed
- [x] Repurpose [rp-ucd-harvest scripts](https://github.com/ucd-library/rp-ucd-harvest/tree/main/lib) for file construction
- [x] Create a jsonld frame to better see the data.

## Outcome

At the conclusion of this task, we will have
- The beginning of a configuration of the ae server
- The ability to view user records in VIVO format, via the fcrepo interface of the AE server

</div>

**Comment by rakunkel-ucd** [comment]
- [ ] Download IAM subset using the profiles API

**Comment by qjhart** [comment]
One ancillary issue about this is getting our profile access figured out.
- [ ] https://github.com/qjhart/ucdi/issues/8

**Comment by qjhart** [comment]
## Outcome

We have successfully demonstrated this import ability.  With the following caveats. 
- We haven't got the proper importing into this project.  This one-off is documented in [research-profiles/iam-only](https://github.com/ucd-library/research-profiles/tree/main/iam-only)
- The docker-compose file is starting up, but we are adding data directly to the fcrepo endpoint using the script below, after the data iam-data is added to the `fcrepo` filesystem. 

``` bash
FCREPO_SUPERUSER=true FCREPO_DIRECT_ACCESS=true fin io import fcrepo --import-from-root --fcrepo-path-type=subpath
```

### Viewing the data

You can get an example of the data at: 

```bash
http http://localhost:3000/fcrepo/rest/person/fff83802ee4f5eb53e6c5324d898d544 Accept:application/ld+json
```

And if you are in the iam-only example, you can frame that with:

```bash
http http://localhost:3000/fcrepo/rest/person/fff83802ee4f5eb53e6c5324d898d544 Accept:application/ld+json | jsonld frame --frame=frame.jsonld.json 
```



Here is an example of the fcrepo representation.
![image](https://user-images.githubusercontent.com/344953/222800947-bb7ef3e7-de40-4b93-aae9-2f06da6db22d.png)

Currently we are storing the metadata as pointing to the official names, and not the name of the fcrepo.  Justin had brought this up as a better plan previously, and we should revisit this issue.  I have started a discussion #23




## TODO

-  Decide on metadata ids, #23.
- Plan for incorporation of the harvest tools into the images.
