### ISSUE TITLE
Users see citations that are as complete as our sources would allow it.

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/aggie-experts#24]
When a user opens their profile page, they see each academic article formatted in APA format, with each of the following fields present:
[APA format for journal articles](https://apastyle.apa.org/style-grammar-guidelines/references/examples/journal-article-references)
Users see  
Title as per UI mockup
Authors,  Year, Journal Title, Volume, Issue, Page or Page Range, DOI. 
Those data elements are displayed as long as they are present in one of the data sources. The DOI is hyperlinked.

[APA format for conference proceedings](https://apastyle.apa.org/style-grammar-guidelines/references/examples/conference-proceeding-references)
Note: if the proceeding is published as a book chapter, our sources do not have data on the editors, so we cannot display that.

[Chapter in an edited book](https://apastyle.apa.org/style-grammar-guidelines/references/examples/edited-book-chapter-references)
Note: our sources don't have data on book editors. This will have to be addressed at a later time.

Currently, there is a ranking of preference for the citation sources, and only the data elements from the available top choice is displayed. At the completion of this epic story, the citations will be as complete as possible with the elements enumerated above, correctly combining data from the different sources as needed. 

- [x] #25
- [x] #40
- [x] #41
- [x] #42
- [x] #43
- [x] #44
- [x] #45
- [x] #46
- [x] #47
- [ ] #48
- [x] #49
- [x] #26
- [x] #27
- [x] #28
- [x] #66
- [x] https://github.com/ucd-library/aggie-experts/issues/93
- [x] https://github.com/ucd-library/aggie-experts/issues/36
- [x] https://github.com/ucd-library/aggie-experts/issues/112
- [x] https://github.com/ucd-library/aggie-experts/pull/194
- [x] https://github.com/ucd-library/aggie-experts/issues/161
- [x] The works portion of https://github.com/ucd-library/aggie-experts/issues/169

Development work based on UI mock-ups: https://github.com/ucd-library/aggie-experts/issues/151
---------------------------------------------------------------------------------------------------------------------------------------------
****Outcome****

Currently, article citation 3469144 appears as
[Hydrological processing of salinity and nitrate in the Salinas Valley agricultural watershed](https://rc.experts.ucdavis.edu/work/3469144) Zikalala P, Kisekka I, Grismer M. Environmental Monitoring and Assessment. 193.

When updated, it will appear as 
[Hydrological processing of salinity and nitrate in the Salinas Valley agricultural watershed](https://rc.experts.ucdavis.edu/work/3469144) Zikalala P, Kisekka I, Grismer M. 193 (Suppl 1): 272.

Currently, conference paper citation 2713713 appears as

[Streaming Satellite Data to Cloud Workflows for On-Demand Computing of Environmental Data Products](https://rc.experts.ucdavis.edu/work/2713713) Zinn D, Hart Q, Ludascher B, Simmhan Y. . 1-8.

When updated, it will appear as

[Streaming Satellite Data to Cloud Workflows for On-Demand Computing of Environmental Data Products](https://rc.experts.ucdavis.edu/work/2713713).  Zinn D, Hart Q, Ludascher B, Simmhan Y. . The 5th Workshop on Workflows in Support of Large-Scale Science. 1-8.
The IEEE publisher's citation also includes location , New Orleans, LA, USA, but none of our sources has that, so we cannot include it.

***Definition of Done***

- [x] UI appearance matches design mockups for Profile with No Subjects with 10 works displayed
- [x] Citations are formatted in APA style
- [x] Most citations have complete data
- [x] UI appearance matches design mockup for Profile -- Works All (20 publications max per page)
- [ ] The total number of works on the profile matches the total number of visible works for that person in Elements
- [x] Work title links will be cold for 2.0
- [x] Clicking on the pages at the bottom will open the next up to 20 works page, in chronological order. 
- [x] Clicking on Return to Profile with return to Profile with No Subjects (same page ok)
- [ ] Sign in takes the user to CAS
- [ ] Approved to move to RC2

**Comment by qjhart** [comment]
The citation source to VIVO construction as been added to the experts-client query, [cdl_citation_to_vivo](https://github.com/ucd-library/aggie-experts/blob/dev/experts-client/queries/cdl_citation_to_vivo.rq ).

These  queries have not formally been added to the experts-cli, but the construction here is approrpiate for the sply funcationality.

**Comment by Vensberg** [comment]
VALUES (?source ?priority) gives the priority of the sources as they fill in gaps in the citation fields

**Comment by qjhart** [comment]
@Vensberg , we haven't yet come up with proper id's for the above works,  but you can find  them  with

```bash 
for i in 3469144 2713713; do id=$(md5sum <<<"http://oapolicy.universityofcalifornia.edu/${i}" | cut -d' ' -f1 | sed -e 's!\(..\)!\1/\1!'); echo $i $id; done
```

``` txt
3469144 fe/fe97dfb56036bbea5b3c3f186b970ce1
2713713 0b/0b9d64001400f6a921cbd8c71cb5d5c0
```

These are now formatted in citation style, so you can see what that APA might look like with: 

```basn
http http://localhost/fcrepo/rest/work/0b/0b9d64001400f6a921cbd8c71cb5d5c0/svc:es-work-transform | jq '.["@graph"][0]' | citation-js -f string -s citation-apa
```

``` text
Streaming satellite data to cloud workflows for on-demand computing of environmental data products. (published). 2010 5th Workshop on Workflows in Support of Large-Scale Science, WORKS 2010. https://doi.org/10.1109/WORKS.2010.5671841
```
Authors are currently not included properly. in the default result, but you can see the container in the above example

**Comment by Vensberg** [comment]
The Publisher appears in the UI, but not in the RIS file download.

**Comment by Vensberg** [comment]
Sources sometimes won't distinguish b/n author and editor. Crossref seems to get this right.
