### ISSUE TITLE
MVP - Version E

### ISSUE THREAD

**Issue by qjhart** [ucd-library/aggie-experts#242]
# Summary

The major goals for this sprint are:
-  have methodology for the CDL grants feed completed ( Plan for move to production in Dec)
- Have an example corpus on test.experts.library.ucdavis.edu
- The users UI experience is completed and ready for QC
- Start to verify the users's ability to alter visibility/rejection of citations; and visibility of grants
- Finalize searching

## Grants
We have pretty much all we need for workflow components. We do need better describe the grants with custom documentation.

- [ ] #223 - Can be updated w/ CDL data and closed
- [x] #248 - Wll be the final documentation
- [ ] #55 - Finalize the new required custom columns for the feed

## Corpus

Once we have the production system setup, we can bring up a version of the system with the initial corpus of users in place.

- [x] #244 - This will house `test` and `rc`
- [x] #251 - Needs to be complete so we can get a complete set of data
- [ ] #240 

##  UI

- [x] #234 
- [x] #186 
- [x] #205 

## Visibility
- [x] #252
- [ ] #253
- [ ] #254

## Search
- [x] #255

## Misc
- [ ] Update permissions on fcrepo experts 
- [ ] Move to aggie-experts cloud
- [ ] Investigate better author support for citations
- [ ] Timing for fuseki
