### ISSUE TITLE
Understand the best source for Journal Titles / Abbreviations

### ISSUE THREAD

**Issue by qjhart** [ucd-library/aggie-experts#36]
Any CDL citation that points to a larger work, like a citation, includes a section on the potential journal titles that could be used for the citation.  Our current methodology doesn't use this, and instead simply uses the journal article that exists in the chosen citation.  

To create instances that share the same title for every citation from any journal, we need to instead get the journal title from the journal sources themselves.

## Tasks
- [x] Import Journals into Main database
- [x] Query on the total number of journals used at UCD
- [x] Count the different number of titles used per journal (per source?)
- [x] Investigate the journal titles in the journal database, look for pub med style titles.  There are *no* journal sources that include this, although TBH, I stopped looking after a convo w/ VE.

## Outcome

At the completion of this examination, we should "
- Have a plan for determining the best Title given the sources that exist for a given citation.
- Understand if valid abbreviated titles exist anywhere in the CDL journal system.
- Have a tentative plan for creating abbreviations for citation types that require them. 

## Results

A more complete description of the journals in CDL is found at [journals.org](https://gist.github.com/qjhart/4cbc784e6d9ad69b38c586fe5984a0b7#file-journals-org)

- Our plan is to use the CDL Elements "official" journal name that's included in each citation (outside the source) 
- This is done, for example with this [citation query](https://github.com/qjhart/aeq/blob/41953cc0894a93bda8febd30a6a98055b76d6d3e/queries/publication.rq#L272)
- We are *Not* inlcuding any abbreviated titles.
- We don't *think* there are abbreviated titles
- We are *not* adding any additional journal information for now.

**Comment by qjhart** [comment]
@Vensberg how does this get reviewed as a valid user story?

**Comment by Vensberg** [comment]
We have an issue that about 5% of our sample is not getting the journal title correct based on the acronym (sometimes titles are expanded beyond what the acronym is intended). We need to asses whether there is a better reconciliation list out there.
