### ISSUE TITLE
Users can see the names and affiliations of all UC Davis faculty in Aggie Experts.

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/aggie-experts#37]
While this epic story is not being broken into smaller user stories,scaling up the application to the entire campus requires rebuilding of the backend. Below are the developer stories that would enable that.
---

- [x] https://github.com/ucd-library/aggie-experts/issues/32
- [ ] https://github.com/ucd-library/aggie-experts/issues/7
- [x] https://github.com/ucd-library/aggie-experts/issues/18
- [x] https://github.com/ucd-library/aggie-experts/issues/85
- [x] https://github.com/ucd-library/aggie-experts/issues/91
- [x] https://github.com/ucd-library/aggie-experts/issues/18
- [x] https://github.com/ucd-library/aggie-experts/issues/107
- [x] UI work: Development work based on UI mock-ups: https://github.com/ucd-library/aggie-experts/issues/151
- [x] https://github.com/ucd-library/aggie-experts/issues/169
- [x] [An initial set of Aggie experts data is available in FCREPO and elastic search#96](https://github.com/ucd-library/aggie-experts/issues/96)
- [x] https://github.com/ucd-library/aggie-experts/issues/190
- [x] https://github.com/ucd-library/aggie-experts/pull/257

-------------------------------------------------------------------------------------------------------------------------------
****Definition of Done****

- [ ] The UI visually reflects the mock up of Profile with No Subjects About Me section
- [ ] Research, teaching, overview summaries are displayed in the Introduction section
- [ ] Titles, emails and websites group together and are displayed in the Roles section
- [ ] Websites sourced from Elements and Author Ids (Scopus ID, Researcher Id, ORCID, others) are displayed the Websites section (may change this)
- [ ] There are no empty sections (the header does not appear if there are no data to show)
- [ ] If a user clicks on an email address, an email template appears
- [ ] If a user clicks on a website link or an Author id link, it opens in a new tab
- [ ] If a user clicks on Sign In, they are taken to authenticate with CAS
- [ ] All users have at least one role and one email address, if they are visible in ODR/PPS
- [ ] The interface responds when the page is resized
- [ ] Only Senate Faculty are included in this iteration
- [ ] The work is approved for move to rc2
