### ISSUE TITLE
Users can search for experts and collaborators by keywords

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/aggie-experts#51]
The users who come looking for collaborators have a range of preferences for the search outcome. In some cases the users want the expert who specialized in the area defined by a particular search field, and not simply a peripheral interest exemplified by a single publication. Other users prefer to cast a wider net for anyone who may have interest in an area. Our users also want to understand the basis for the search results. Transparency is key. They would often want to further follow up and see the website of the faculty to get a more complete picture about their interests. 
The outcome of a successful search is that the user would want to contact the faculty, so an export of the search results needs to take that into account.
A few notes: 
* A bio is the fastest way for a user to make a conclusion about the faculty's research interest. However, the need for manual updates can create issues with their currency. Perhaps, a separate update date for the bio should be considered.
* Grants, especially active grants, reflect current research focus

Even though search should be able to surface publications and grants by keywords, what most users are looking for are people. The key question asked is "Who is doing research on [keywords]?"

- [x] #70
     Getting built out here:
          - [ ] https://github.com/ucd-library/aggie-experts/issues/104 
          - [ ] https://github.com/ucd-library/aggie-experts/issues/110
          - [ ] https://github.com/ucd-library/aggie-experts/issues/150
- [x] #71
- [x] #72

- [x] #73

- [x] #75

- [x] UI mockups for search 2.0
- [x] https://github.com/ucd-library/aggie-experts/issues/186
- [x] See Basic search portion of https://github.com/ucd-library/aggie-experts/issues/185

---
Outcome
Users should be able to search for experts they are familiar with by keywords about their research and see those researchers within the top 10 results.

***Definition of Done***

- [x] A user types in a keyword in the search bar on the home page and the search results page opens in the same window.
- [x] The UI visually reflects the mock up of [insert Search mockup name here]
- [x] When the user clicks on Lastname, First name, the person's profile opens in a new tab
- [x] Search matches: # grants * # works links are cold
- [ ] When the user clicks "Select All", all boxes on the page get checked. That includes all results of the search, not just the current page. If there are more than 100 results
- [x] When a user clicks on the Download button, a CSV with the checked results is downloaded (See https://github.com/ucd-library/aggie-experts/issues/77 for CSV content)
- [ ] A manual check for titles of works with a keyword on a person's profile matches the # works shown by the search

**Comment by Vensberg** [comment]
Several of these issues are too granular, and the approach in https://github.com/ucd-library/aggie-experts/issues/104 will resolve all of them.
