### ISSUE TITLE
Users can see their grants represented on their profile pages

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/aggie-experts#55]
A substantial portion of this epic story was completed during the pilot with College of Engineering in 2022. The following are the remaining tasks as we are preparing to change the source for grants.
     
- [x] #67
   This is getting addressed in
          https://github.com/ucd-library/aggie-experts/issues/143
          https://github.com/ucd-library/aggie-experts/issues/144
- [x] #68
   
- [x] Ensure Archive Grants Feed to Elements is functional. https://github.com/ucd-library/aggie-experts/issues/223

- [x] Advocate for integration with universal identifiers such as FundRef
    Initial steps https://github.com/ucd-library/aggie-experts/issues/147

Development work based on UI mock-ups: https://github.com/ucd-library/aggie-experts/issues/151

Definition of Done:

- [ ]  Rename the following fields in the grants to allow easier cross-walk with MIV fields
* Default type --> Research
*  Instruction --> Teaching and Training
* Academic Support --> Teaching and Training
* Service / Other --> TBD, @Vensberg needs to consult Academic Affairs.

**These were the roles in KFS, and as such probably shouldn't be changed for  the archive. We will have to do  this in the UI.  See also #223**

- [x] Data elements of the grant that should be represented on the UI
* Title, Dates, Type of Grant, Role (PI or CoPI, and key personnel from the archived grants, Funder)

**What about Funder ID , Flow Through Funding (federal)?**

- [x] Data elements of the grant that should be included in the download from each user's account admin interface
* Title, Dates, Type of Grant, Role (PI or CoPI, and key personnel from the archived grants, Funder), Grant id from the funder
- [x] Data elements of the grant citation that should be included in the download from each search
* Title, Dates, Type of Grant, Role (PI or CoPI, and key personnel from the archived grants, Funder), Grant id from the funder
- [ ] For the archived grants, grants on rc match grants on sandbox
- [x] Grants data on the UI matches UI mockups
- [x] There are no hot links at this time

**Comment by UcDust** [comment]
@Vensberg @wrenaria 

Here's a sample of how the grants are currently displayed.

<img width="1034" alt="Screenshot 2023-10-25 at 07 21 56" src="https://github.com/ucd-library/aggie-experts/assets/103536473/591810cc-26b6-4c5c-b5e2-fb24e839ca59">

1. Any issues with the content you'd like addressed? I think there's still an open task related to expert titles/roles, where we're trying to determine a good way of standardizing the character case, I imagine whatever the outcome there will affect the mix of uppercase/lowercase seen here.
2. What should the download contain? I think it's csv right? What type of headers/data should it contain?

**Comment by Vensberg** [comment]
Nothing jumps out at me at this point. I need to think more about the type of grant, but this is a good representation as it is.

**Comment by Vensberg** [comment]
The download csv should contain
Title | Funding Agency | Grant id {the one given by the agency, not ours} | Start date | End date | Type of Grant | List of contributors (role) {separate contributors by ";"} |

**Comment by Vensberg** [comment]
Comparison of MIV fields vs the grant fields that we have

Mandatory fields 

Type: Research ; Teaching and Training ; Service ; Academic Support ; Student Support ; Scholarships/ Fellowships ; Other
[Note: our categories are different Academic Support; Default; Instruction ; Research; Service / Other	]

Status: Active ; Submitted; Completed; Not Awarded ; None
[Note: our categories are only Active and Completed]

Grant/Contract/Gift Title [free text]

Amount $ 

Role: Principal Investigator; Co-Principal Investigator; Co-Investigator; Assistant Researcher; Collaborator; Instructor; Trainer; Other
[Note: our fields are only PI, coPI]


Non-mandatory fields 
* that we can supply:
Funding Agency:
Grant Number:
* that we may supply with Aggie Enterprise
Total number of PIs/Co-PIs
List all PIs and Co-PIs, including yourself


* That we cannot supply
Off-Campus Amount:

Either the Start Date or the Submitted/Resubmitted Date must be entered.
Start Date: ...       End Date: ... 
and/or Submitted/Resubmitted Date: 
Percent Effort: 
 
URL:
Purpose/Goal of the grant:
 Contributions to grant or contract:

**Comment by Vensberg** [comment]
Definition of Done:

**Comment by Vensberg** [comment]
For QC on grants I'd like an[ updated spreadsheet ](https://docs.google.com/spreadsheets/d/1X2W-ohJwtblfGdXdA7lAJJn2sqKvS9tIEd8sR3aospY/edit#gid=0) with just the users with grants.

**Comment by UcDust** [comment]
@Vensberg I've added this task into the current sprint, I plan to work off of this for the grant csv download.

**Comment by Vensberg** [comment]
@UcDust, there are issues with grants data, which is why they are not displaying correctly on the interface. Roger identified them and will be reuploading. After that, the data should be pulled down again and I will QA again.

**Comment by Vensberg** [comment]
@UcDust @qjhart I added some renamings that are needed to cross-walk our terminology to MIV. (See Definition of Done added to the original entry). I am not sure who would handle that.

**Comment by Vensberg** [comment]
@UcDust , @rakunkel-ucd , @qjhart , RGPO grants don't have a "type". I propose they be labeled as "Research" on import.
