### ISSUE TITLE
Testing 

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/aggie-experts#568]
### Test date
7/25/2024
Stage

### Reason for testing:
- [ ] New feature
- [ ] New data
- [x] New release

### Key changes to test
- [x] Citations with >40 authors don't display all data (download work)
- [x] Drop down menu collapses after navigating to Profile/ Help page

### Tasks
- [x] Impersonate a user using keycloak
- [x] Confirm works can be downloaded from the profile
- [x] Confirm grants can be downloaded from the profile
- [x] Navigate to their Edit Works; review citations
- [x] Download a single work
- [x] Change visibility of a work and confirm change in Elements
- [x] Reverse visibility through AE UI
- [x] Navigate to their Edit grants; review citations
- [x] Download a single grant
- [x] Change visibility of a grant and confirm change in Elements
- [x] Reverse visibility through AE UI

### More extensive testing
- [ ] As an admin search for 0130. There should be only one hit
- [ ] Edit user and hide that grant
- [ ] Repeat search: confirm no results are returned
- [ ] Review grants CSV download, particularly coPI list
- [ ] Ask for a broken links review

### Before a live demo
- [ ] Download a RIS file of publications and test import into MIV
- [ ] Test pulling grants into MIV

### After a particularly major update
- [ ] Go to Browse-->M. Check that pagination works right
- [ ] Go to faculty with hundreds of publications: Check pagination again
- [ ] Edit user: check that Add work redirects to Elements
- [ ] Edit userL Check that bio fields redirect to Elements

**Comment by Vensberg** [comment]
Review connection to Elements once the code is on production.
