### ISSUE TITLE
Testing stage with new federation data

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/aggie-experts#581]
### Reason for testing:
- [ ] New feature
- [x] New data

### Tasks
- [x] Impersonate a user using keycloak
- [x] Confirm works can be downloaded from the profile
- [x] Confirm grants can be downloaded from the profile
- [x] Navigate to their Edit Works; review citations
- [x] Download a signel work
- [x] Change visibility of a work and confirm change in Elements
- [x] Reverse visibility through AE UI
- [x] Navigate to their Edit grants; review citations
- [x] Download a single grant
- [x] Change visibility of a grant and confirm change in Elements
- [ ] Reverse visibility through AE UI

### More extensive testing
- [ ] As an admin search for 0130. There should be only one hit
- [ ] Edit user and hide that grant
- [ ] Repeat search: confirm no results are returned
- [ ] Review grants CSV download, particularly coPI list
- [ ] Ask for a broken links review

### Before a live demo
- [ ] Download a RIS file of publications and test import into MIV
- [ ] Test pulling grants into MIV

### After a particularly major update
- [ ] Go to Browse-->M. Check that pagination works right
- [ ] Go to faculty with hundreds of publications: Check pagination again
- [ ] Edit user: check that Add work redirects to Elements
- [ ] Edit userL Check that bio fields redirect to Elements

**Comment by Vensberg** [comment]
Note the Test grant.

**Comment by Vensberg** [comment]
@qjhart 
Some users don't have titles and affiliations listed. Examples: 
expert/QglTyzLH
expert/QQSQFMX4
expert/H240UBcp
Other than that, things work as expected.

**Comment by qjhart** [comment]
## Bad ODR records

@Vensberg for the examples that you gave, we have a curious problem.  Each of these users have an ODR record.  Our current logic is that if any ODR record exists, then we use only ODR records, and no PPS records. However, ODR records also allow incomplete records to be included (like a user might not show their dept eg)  So, we make all the ODR record fields optional.  In these users' case their ODR records all all null values.  So we are doing what we logically said, showing all the none data they've added.  The online directory system, must have logic to ignore all null values.  We could do the same and requitre that for example title is always filled out, or we won't use the ODR  record.  

Alternatively, we could modify the UI, and ask @UcDust to add logic where if no contact info `isPreferred` use that default version.  (The one outside the graph)

QglTyzLH (aaccorsi@ucdavis.edu)  
QQSQFMX4 (axaggarwal@ucdavis.edu) 
H240UBcp (sagraw@ucdavis.edu)

Here's the example for `ucdid fetch --search=email=aaccorsi@ucdavis.edu profiles`

```json
      "listings": [
        {
          "listingOrder": 1,
          "deptCode": null,
          "deptName": null,
          "deptWwwFlag": "Y",
          "deptUcdFlag": "Y",
          "title": null,
          "titleWwwFlag": "Y",
          "titleUcdFlag": "Y",
          "website": null,
          "websiteWwwFlag": "Y",
          "websiteUcdFlag": "Y",
          "email": null,
          "emailWwwFlag": "Y",
          "emailUcdFlag": "Y",
          "location": null,
          "device": null,
          "createDate": "2023-07-17 16:10:35",
          "modifyDate": "2024-07-19 02:21:50"
        }
```

**Comment by qjhart** [comment]
I'd suggest we either require 'title' or 'title` and `dept`

**Comment by qjhart** [comment]
There are actually *a lot* (2400) of entries with this problem

```sparql
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ucdlib:  <http://schema.library.ucdavis.edu/schema#>
select distinct ?sub ?email
WHERE {
  graph ?g {
  ?sub a vivo:FacultyMember;
    ucdlib:email ?email;
        .
    MINUS {
	  ?sub obo:ARG_2000028/ucdlib:isPreferred true.
    }      
  }
}
```
