### ISSUE TITLE
Testing Availability Labels -- include search

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/aggie-experts#592]
### Reason for testing:
- [x ] New feature
- [ ] New data

### Tasks
- [x] Impersonate a user using keycloak
- [ ] Confirm works can be downloaded from the profile
- [x] Confirm grants can be downloaded from the profile
- [x] Change availability for community and confirm change in Elements
- [x] Change availability for media and confirm change in Elements
- [x] Change availability for collaborations and confirm change in Elements
- [x] Change availability for industry and confirm change in Elements
- [x] Reverse availability through AE UI
- [x] Search for "influenza"
- [x] Select community filter. Confirm that search returns only results with that label in the profile.
- [x] Select media filter. Confirm that search returns only results with that label in the profile.
- [x] Select collaboration filter. Confirm that search returns only results with that label in the profile. (0 at this time)
- [x] Select industry filter. Confirm that search returns only results with that label in the profile.  (0 at this time)
- [x] Select community AND media filter. Confirm that search returns only results with that label in the profile.

**Comment by Vensberg** [comment]
@wrenaria , Could you advise on the following?
Currently, if I click on the search lens, but don't enter keywords, search will not return results. It makes sense not to want to return the entire roster. But then, I am trying to think through the following scenario: when no search terms are entered, but filters are selected,  should they continue to return no results or should they filter on the entire collection? Or prompt for a keyword entry?

**Comment by Vensberg** [comment]
The availability labels work well. I just want Kimmy's feedback on my comment above.

I found several different bugs though.
@UcDust , expert/Z69UnXfY profile won't load publications for editing. Broken on production as well.
I also made a mistake on the home page search tip. It's not an "AND" search, but an "OR" search. Can you change that in the text?
@qjhart, expert/g9XxoCvk is missing their email address. It is present on production.  Same for expert/sOOiOizO. 
expert/1vNytFen is missing roles and email. Production is just missing their email. 
A lot of users are missing emails, both federation and senate.

**Comment by qjhart** [comment]
@Vensberg stage has been updated for emails.  Today, I'll count the number of experts affected bythe IAM, bug, and see about a one time solution

**Comment by wrenaria** [comment]
> @wrenaria , Could you advise on the following? Currently, if I click on the search lens, but don't enter keywords, search will not return results. It makes sense not to want to return the entire roster. But then, I am trying to think through the following scenario: when no search terms are entered, but filters are selected, should they continue to return no results or should they filter on the entire collection? Or prompt for a keyword entry?

I've seen it done both ways. I suppose I am inclined towards showing everything from that category in the results if a filter is selected (if no filter selected + an empty search query, do nothing). Granted we do have plans for browse-oriented pages, so I am okay with either choice.
