### ISSUE TITLE
Testing Grant Landing Page

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/aggie-experts#622]
### Test date
10/2/2024

### Reason for testing:
- [x] New feature
- [ ] New data

### Tasks
- [ ] Impersonate a user using keycloak
- [ ] Confirm works can be downloaded from the profile
- [ ] Confirm grants can be downloaded from the profile
- [ ] Navigate to their Edit Works; review citations
- [ ] Download a signel work
- [ ] Change visibility of a work and confirm change in Elements
- [ ] Reverse visibility through AE UI
- [ ] Navigate to their Edit grants; review citations
- [ ] Download a single grant
- [ ] Change visibility of a grant and confirm change in Elements
- [ ] Reverse visibility through AE UI

### More extensive testing
- [ ] As an admin search for 0130. There should be only one hit
- [ ] Edit user and hide that grant
- [ ] Repeat search: confirm no results are returned
- [ ] Review grants CSV download, particularly coPI list
- [ ] Ask for a broken links review

### Before a live demo
- [ ] Download a RIS file of publications and test import into MIV
- [ ] Test pulling grants into MIV

### After a particularly major update
- [ ] Go to Browse-->M. Check that pagination works right
- [ ] Go to faculty with hundreds of publications: Check pagination again
- [ ] Edit user: check that Add work redirects to Elements
- [ ] Edit userL Check that bio fields redirect to Elements

**Comment by Vensberg** [comment]
Correct choice: the mockups have the amount showing, but correctly, the page does not display that.

@UcDust , currently the Grant Admin field displays the same entity as Awarded by. It is likely the data did not make it. While that is being inspected, please, hide the Grant Admin field until we know more.

Invisible grants still have resolvable landing pages. When the grant visibility has been changed, the expected behavior is:
1. If there are no public relationships, the grant landing page should return a 404 for all users, including the owner of the grant
2. If there are other experts related to the grant, the grant landing page will continue to resolve, but 
--if the expert who changed the visibility setting is a PI or coPI, their name will continue to appear in the list of contributors, but not link back to their profile page
--if that expert is a different type of contributor, they will be removed from the list of contributors

**Comment by UcDust** [comment]
@Vensberg 

The first item of removing the grant admin field from the ui will be done in https://github.com/ucd-library/aggie-experts/pull/625.

The second item for the 404 page when no public contributors, and other display preferences you outlined, will be done in https://github.com/ucd-library/aggie-experts/pull/621.

**Comment by Vensberg** [comment]
10/15/2024
Retest

@UcDust, on [this grant ](https://stage.experts.library.ucdavis.edu/grant/ark:/87287/d7gt0q/grant/K382939-102424) and [this one](https://stage.experts.library.ucdavis.edu/grant/ark:/87287/d7gt0q/grant/K326C67-122698) Contributors are being duplicated. Also, can you make the font and letter case the same for linked and non-linked contributors?

**Comment by Vensberg** [comment]
The grant admin field has been successfully removed.

**Comment by Vensberg** [comment]
The 404 issue is almost done. What works well:
* If the expert is the only person on the grant, it gives a 404
* If the expert is a non-PI personnel, they disappear, the grant and PIs who are still at UCD stay
What needs fixing
* If the PI/coPI are no longer active UCD personnel, and the expert who changes the visibility on their grant to invisible is the last active link, this grant needs to give a 404 (example of [that type of grant](https://stage.experts.library.ucdavis.edu/grant/ark:/87287/d7gt0q/grant/K328235-111109), with Quinn making that grant invisible should give 404)

**Comment by UcDust** [comment]
@Vensberg 

The issue related to the 404 page from your last comment should now be fixed and on stage.

**Comment by qjhart** [comment]
@Vensberg stage is now at 2.2.3, incorporating #638, #636, and #632. 
We can't fix duplicate names till version 2.3

**Comment by Vensberg** [comment]
@UcDust, looks good.
