### ISSUE TITLE
Testing full script after grants search

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/aggie-experts#660]
### Reason for testing:
- [ ] New feature
- [ ] New data

### Tasks
- [ ] Impersonate a user using keycloak
- [ ] Confirm works can be downloaded from the profile
- [ ] Confirm grants can be downloaded from the profile
- [ ] Navigate to their Edit Works; review citations
- [ ] Download a signel work
- [ ] Change visibility of a work and confirm change in Elements
- [ ] Reverse visibility through AE UI
- [ ] Navigate to their Edit grants; review citations
- [ ] Download a single grant
- [ ] Change visibility of a grant and confirm change in Elements
- [ ] Reverse visibility through AE UI

### More extensive testing
- [ ] As an admin search for 0130. There should be only one hit
- [ ] Edit user and hide that grant
- [ ] Repeat search: confirm no results are returned
- [ ] Review grants CSV download, particularly coPI list
- [ ] Ask for a broken links review

### Before a live demo
- [ ] Download a RIS file of publications and test import into MIV
- [ ] Test pulling grants into MIV

### After a particularly major update
- [ ] Go to Browse-->M. Check that pagination works right
- [ ] Go to faculty with hundreds of publications: Check pagination again
- [ ] Edit user: check that Add work redirects to Elements
- [ ] Edit userL Check that bio fields redirect to Elements

**Comment by Vensberg** [comment]
Will be tested with the expanded script in https://github.com/ucd-library/aggie-experts/issues/672
