### ISSUE TITLE
Testing Grants Search

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/aggie-experts#672]
### Reason for testing:
- [x] New feature
- [x] New data: we got ~150 new users

### Tasks
- [x] Impersonate a user using keycloak
- [x] Confirm works can be downloaded from the profile
- [x] Confirm grants can be downloaded from the profile
- [x] Navigate to their Edit Works; review citations
- [x] Download a single work
- [ ] Change visibility of a work and confirm change in Elements -- not in Elements, yes on the interface
- [ ] Reverse visibility through AE UI -- hold
- [x] Navigate to their Edit grants; review citations
- [x] Download a single grant
- [x] Change visibility of a grant and confirm change in Elements
- [x] Reverse visibility through AE UI
- [x] Search for avian flu. Confirm that searches have "search matches: # grants.
- [ ] Test download on:
      - [ ] All Results--expert only
      - [x] Experts
      - [ ] Grants--no
      - [ ] Works (Currently N/A)
- [x] Under Experts check and uncheck Availability labels. Note that the number of experts changes appropriately.
- [x] Test download
- [x] Click on the # grant for one of the experts. A filter with the name should appear, and only those grants should be listed
- [ ] Check download--no

### More extensive testing
- [ ] As an admin search for 0130. There should be only one hit: old data. Now there are three. Need to rethink this test.
- [x] Edit user and hide that grant
- [ ] Repeat search: confirm no results are returned --nope
- [ ] Review grants CSV download, particularly coPI list
- [ ] Ask for a broken links review

### Before a live demo
- [x] Download a RIS file of publications and test import into MIV
- [ ] Test pulling grants into MIV -- skip, can't test stage

### After a particularly major update
- [x] Go to Browse-->M. Check that pagination works right
- [x] Go to faculty with hundreds of publications: Check pagination again
- [x] Edit user: check that Add work redirects to Elements
- [x] Edit userL Check that bio fields redirect to Elements
- [x] New users are added

**Comment by Vensberg** [comment]
@UcDust , the grants are not currently download-able from Search --> All Results, Grants and Grants filtered by Expert.

**Comment by Vensberg** [comment]
@wrenaria, there is a # category in [Expert Browse](https://experts.ucdavis.edu/browse/expert/a) (I assume based on the Grants Browse). I wanted to confirm with you that choice.

**Comment by Vensberg** [comment]
Search doesn't reset.
I did an initial search on "avian flu" and selected an expert.
Then I typed "lane". The search didn't change. The URL initially correctly had "lane" as the query, but a second click on the search changed it to ?q=lane&expert=expert/4gQyiBPO. The UI display of results didn't change (see screenshot). Also, the Select All for Download did not.
<img width="927" alt="search" src="https://github.com/user-attachments/assets/6fc8b4c3-ec6b-47d9-add8-2c744828fa3b" />

**Comment by Vensberg** [comment]
To address at a later time: when redirecting a user to add a bio/an intro to Elements, the landing page should be their profile in editing mode rather in viewing mode.

**Comment by UcDust** [comment]
@Vensberg @qjhart @wrenaria 
I'm not sure how best to approach the grant download on the search page. Currently only experts can be downloaded there, and the headers for that data are:

```
Name | Aggie Experts Webpage | Number of works that match the keyword | Number of grants that match the keyword | URLs from the profile
```

What data should be extracted for grants? How should we handle when the download is a combination of both types of results? Also there's the new design for complex search results that's pending design, so not sure if that will affect when the changes here are delivered.

**Comment by Vensberg** [comment]
@UcDust , grants from the search-grants filter should be downloadable with the same headers as from the researcher's profile:  

Title | Funding Agency | Grant Id | Start Date | End Date | Type of Grant | Role | List of PIs and   CoPIs

Perhaps, for the time being Download of All Results should be disabled. Let's do that if Kimmy has no objections.

**Comment by UcDust** [comment]
> Search doesn't reset. I did an initial search on "avian flu" and selected an expert. Then I typed "lane". The search didn't change. The URL initially correctly had "lane" as the query, but a second click on the search changed it to ?q=lane&expert=expert/4gQyiBPO. The UI display of results didn't change (see screenshot). Also, the Select All for Download did not reset. <img alt="search" width="927" src="https://private-user-images.githubusercontent.com/26015534/394968557-6fc8b4c3-ec6b-47d9-add8-2c744828fa3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNDc3NjMsIm5iZiI6MTczNDA0NzQ2MywicGF0aCI6Ii8yNjAxNTUzNC8zOTQ5Njg1NTctNmZjOGI0YzMtZWM2Yi00N2Q5LWFkZDgtMmM3NDQ4MjhmYTNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDIzNTEwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4M2FiMzExYTg0MDYwMmQ5OTc5NWRhOTc5NzJmYThmYzNlYjgwMmQ4ZGNhMDZjYTc0M2E0NzZkYWM4ZmY5ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.m2JLGbM6SIQvTfQ-N-F8cp0Ln0CFMlM6I_f84lZLoyI">

I guess the intended behavior will be the following:

- When filtered to an experts grants, searches will further refine the results for that expert. If you click on _Expert_ or _All Results_, then the filter to that person will be removed.
- New searches shouldn’t change the filter to all results, search should keep in current filter (ie experts or grants).

**Comment by Vensberg** [comment]
> I guess the intended behavior will be the following:
> 
>     * When filtered to an experts grants, searches will further refine the results for that expert. If you click on _Expert_ or _All Results_, then the filter to that person will be removed.
In both cases the filter should remain. In the described case the search+filters currently operate as expected
>     * New searches shouldn’t change the filter to all results, search should keep in current filter (ie experts or grants).
With a new search all existing filters should go away. In the example above, when the user types "Lane" and hit search, the search page should load All Results and the query should be search?q=lane

**Comment by Vensberg** [comment]
@UcDust , @qjhart do you expect stage to be able to propagate changes to Elements at this time?

**Comment by Vensberg** [comment]
Definitely  a bug

**Comment by Vensberg** [comment]
@qjhart, @UcDust --unexpected behavior on hidden grant and search. Searching for a part of the title of a grant returns it in search and reverses visibility. I tested this as an admin. I'll check in other roles.

**Comment by Vensberg** [comment]
> @qjhart, @UcDust --unexpected behavior on hidden grant and search. Searching for a part of the title of a grant returns it in search and reverses visibility. I tested this as an admin. I'll check in other roles.
Correction, on another try the grant has become invisible on the profile. However, it still appears in search.
