### ISSUE TITLE
Re-Testing Grant Search

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/aggie-experts#685]
### Reason for testing:
- [x] New feature
- [x] New data
- [x] Fixes from https://github.com/ucd-library/aggie-experts/issues/672

### Tasks
- [x] Impersonate a user using keycloak
- [x] Confirm works can be downloaded from the profile
- [x] Confirm grants can be downloaded from the profile
- [x] Navigate to their Edit Works; review citations
- [x] Download a single work
- [x] Change visibility of a work and confirm change in Elements
- [x] Reverse visibility through AE UI
- [x] Navigate to their Edit grants; review citations
- [x] Download a single grant
- [x] Change visibility of a grant and confirm change in Elements
- [x] Reverse visibility through AE UI
- [x] Search for avian flu. Confirm that searches have "search matches: # grants.
- [x] Test download on:
      - [x] Does not show All Results
      - [x] Experts
      - [x] Does not show on Grants
- [x] Under Experts check and uncheck Availability labels. Note that the number of experts changes appropriately.
- [x] Click on the # grant for one of the experts. A filter with the name should appear, and only those grants should be listed

### More extensive testing
- [x] As an admin search for 0130. There are now 3 experts, 3 grants. But only one grant has it in the title.
- [x] Edit user and hide that grant
- [x] Repeat search: confirm no results are returned--after refresh
- [x] Review grants CSV download, particularly coPI list

### Before a live demo
- [ ] Download a RIS file of publications and test import into MIV
- [ ] Test pulling grants into MIV

### After a particularly major update
- [x] Go to Browse-->M. Check that pagination works right
- [ ] Go to faculty with hundreds of publications: Check pagination again
- [ ] Edit user: check that Add work redirects to Elements
- [ ] Edit userL Check that bio fields redirect to Elements

**Comment by Vensberg** [comment]
Refresh issue: make changes to the grant visibility
Return to Profile (through the link on top)
The visibility of the grant is unchanged.
Refresh
Now it is accurate

**Comment by Vensberg** [comment]
@UcDust , @qjhart , another unexpected behavior:
Go to Browse, Letter M
Click on the ... in pagination
Try to search. I have different outcomes:
1) I get stuck on M
2) I get to search, but the search query is "". Refresh gets me back to M
