### ISSUE TITLE
Users can see all of UC Davis citations in Aggie Experts

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/aggie-experts#69]
This Epic builds on the rearchitecturing of the backend of AE to handle all campus faculty scholarship and the work on creating complete citations. As the largest data subset, this will be a key test to the robustness of the application.

- [x] https://github.com/ucd-library/aggie-experts/issues/86 (Load all citations from Elements and assess the performance of the application)
- [ ] Authorship tasks to be added
- [x] Important: any paper that doesn't have an authorship (was rejected in Elements) will be removed from the dataset
- [x] Admin can remove any citation from AE
- [x] https://github.com/ucd-library/aggie-experts/issues/108 This will allow us to run SPARQL queries on all the data
- [x] Any UI work
- [x] Citations are formatted in APA format (which will resolve the issue of how to display citations with large number of authors)
- [x] The works portion of https://github.com/ucd-library/aggie-experts/issues/169
